# Generated by Django 6.0 on 2025-12-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil_min_cartons',
            field=models.PositiveIntegerField(default=2, help_text='Nombre minimum de cartons avant alerte stock faible'),
        ),
    ]
